### ISSUE TITLE
Creation table evenement

### ISSUE THREAD

**Issue by Ferrer-Jeremy** [Ferrer-Jeremy/Criminalite#2]
Le fichier sql qui crée les tables événements ne marche pas au niveau de la foreign key
- [x] Régler le probleme
- [x] Enlever les lignes create database et use vu que ces tables seront dans la meme DB que les infractions

**Comment by AdrienCHAMPLIAUD** [comment]
Résolution du problème de FK les id n'avait pas le même format l'un UNSIGNED ET pas l'autre 
Ajout d'un fichier sql de creation de base commun aux infractions et évènements.
